export interface IUser{
    id : number;
    name : string;
    username : string;
    email : string;
    address : string;
    street : string;
    suite : string;
    city : string;
    zipcode : number;
    geo : string;
    lat : number;
    lng : number;
    phone : number;
    website : string;
    company : string;
    catchPhrase : string;
    bs : string;
}